### ISSUE TITLE
[FEATURE request] Command-line interface and language-agnostic configuration language

### ISSUE THREAD

**Issue by SamuelMarks** [chipsenkbeil/service-manager-rs#20]
For use in other languages, it would be great to expose a C FFI and (more easily done first) a CLI interface with a language-agnostic configuration language, something like:

```yml
# Global to all service-manager-rs
constants: &global_const
   ${if_win}:
      exe: ".exe"
   ${if_not_win}:
      exe: ""
```

Then you'd roughly have:
```yml
name: service_name
constants:
    prefix:
        ${if_win}:
            "%TMP%\foo" &prefix
        ${if_not_win}:
            "/tmp/foo" &prefix
lifecycle:
   start:  my_init*global_const.exe --prefix *constants.prefix start
   reload: my_init*global_const.exe --prefix *constants.prefix reload
   stop:   my_init*global_const.exe --prefix *constants.prefix stop
```

Which could be used like so:
```sh
$ server-manager install -c "my_yaml_file.yml"
$ server-manager remove "service_name"
```

And alternatively be specified all at the CLI:
```sh
$ server-manager install "my_init" --start "my_init start" --reload "my_init reload" --stop "my_init stop"
$ server-manager remove  "my_init"
```
